[workspace]
members = [
    "spdk-core",
    "backend-blindbit-native",
]
resolver = "2"

[workspace.dependencies]
# Internal workspace crates
spdk-core = { path = "spdk-core", version = "0.1.0" }

# Core dependencies - shared across crates
silentpayments = "0.4"
anyhow = "1.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
bitcoin = { version = "0.31.1", features = ["serde", "rand", "base64"] }
rayon = "1.10.0"
futures = "0.3"
futures-util = "0.3.31"
async-trait = "0.1"
log = "0.4"
hex = { version = "0.4.3", features = ["serde"] }
bdk_coin_select = "0.4.0"
tokio = { version = "1.48.0", features = ["rt"], default-features = false }
reqwest = { version = "0.12.26", features = ["json", "gzip"], default-features = false }

[workspace.package]
repository = "https://github.com/cygnet3/spdk"
