[package]
name = "backend-blindbit-v1"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
spdk-core = { path = "../spdk-core" }

anyhow = "1.0"
async-trait = "0.1"
futures = "0.3"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
reqwest = { version = "0.12.4", features = [
  "rustls-tls",
  "gzip",
  "json",
], default-features = false }
hex = { version = "0.4.3", features = ["serde"] }
